---
- name: Get new certificate
  command: 'kubeadm init phase upload-certs --upload-certs'
  changed_when: false
  run_once: true
  delegate_to: '{{ groups.master[0] }}'
  register: reg_certificate

- name: Get Kubernetes master join command
  command: 'kubeadm token create --print-join-command --certificate-key {{ reg_certificate.stdout_lines[-1] }}'
  changed_when: false
  run_once: true
  delegate_to: '{{ groups.master[0] }}'
  register: reg_join

- name: Join Kubernetes master
  command:
    cmd: '{{ reg_join.stdout }}'
    creates: /etc/kubernetes/admin.conf

- name: Create Kubernetes configuration folder
  file:
    path: '{{ kubernetes_config }}'
    state: directory
  become: false

- name: Get Kubernetes configuration
  copy:
    src: /etc/kubernetes/admin.conf
    dest: '{{ kubernetes_config }}/config'
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
    mode: 'u=rw,g=r,o=r'
    remote_src: yes
